### ISSUE TITLE
timeout

### ISSUE THREAD

**Issue by Junky2008** [attie/libxbee3#17]
When running the library on an ARM board (compiled with arm-linux-gnueabihf-). The program starts correctly but when sending a command to the xbee I always receive a timeout.
The xbee does receive the command and reacts to it, it seems the library does not read the response from the xbee.
I'm trying to debug the threads but I can't confirm that they are running. Any pointers would be appreciated!

**Comment by Junky2008** [comment]
On further inspection it seems the rx thread is stuck on the info->ioFunc function. I'm using the xbeeZB and xbee2.

**Comment by attie** [comment]
Hello,

I'd imagine that this is due to hardware flow control not being setup
properly...

If you don't want to use the hardware flow control (CTS/RTS), then take a
look at config.mk, and uncomment the following line:
OPTIONS+= XBEE_NO_RTSCTS

Attie

**Comment by Junky2008** [comment]
Got it! It seems the library will use two stop bits when using 115200 baud. Now it does work. 
I still have a question though. I'm trying to send data to 24 nodes, the data is unicasted. 
When a node receives the data it responds with 2 messages (including the 8B message that is 3 messages returned for every message sent) 
When I'm sending all 24 messages with a 100ms delay between them, the first 10 work perfectly, but the rest will sometimes return a transmission state 24. How should I address this? 

(ps. Should I make a separate issue for this?)

**Comment by attie** [comment]
Ah yes, This is something that the XBee modules historically enforced...
apologies if it's no longer true.

Do you know what the 24 relates to?
It's very possible that you are using up all of the available bandwidth at
that point in time...
The XBee will implement some retires, and the underlying 802.15.4 protocol
permits a number of retries as well... if these are exhausted then the
message won't be sent.
A better approach might be to have each node back-off by a 'random' time so
that their responses aren't directly on top of each other.

If you have the time, then another approach would be to hold the
conversation with each of the 24 nodes in turn, allowing them to respond
individually in their own time, rather than fighting for the bandwidth.

Attie
